### ISSUE TITLE
error,, python newbie

### ISSUE THREAD

**Issue by adgjmptw2** [Jungyu-Choi/SABot#1]
![image](https://user-images.githubusercontent.com/41006577/108343687-925c3080-721f-11eb-9cf2-6b3b16ad72cb.png)
sry to ask..

**Comment by adgjmptw2** [comment]
File "C:\Users\123\Desktop\SABot-master\SABot.py", line 25, in <module>
    setup = sabot()
  File "C:\Users\123\Desktop\SABot-master\SABot.py", line 21, in __init__
    self.wt = watcher.watcher()
  File "C:\Users\123\Desktop\SABot-master\watcher.py", line 21, in __init__
    with open(".mongodb", "r", encoding="utf-8") as t:
FileNotFoundError: [Errno 2] No such file or directory: '.mongodb'

C:\Users\123\Desktop\SABot-master>
now this error

**Comment by adgjmptw2** [comment]
sry

**Comment by devwithpug** [comment]
안녕하세요. 한국인이신거 같아서 한국어로 편하게 말씀드릴게요.
제가 READMD.md를 수정하지 않았네요.

.token / .riot_api_key  두 파일처럼
.mongodb 파일 또한 필요합니다..!

이 파일은 몽고DB의 Cluster 접속 코드인데요,
내용은 아래와 같습니다.

>mongodb+srv//(본인의 몽고DB 클러스터 접속 주소)

감사합니다!
