### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by adgjmptw2** [Jungyu-Choi/SABot#2]
![image](https://user-images.githubusercontent.com/41006577/108382388-20e6a700-724c-11eb-8049-bd300bc844b8.png)
this error

**Comment by devwithpug** [comment]
안녕하세요. 해당 오류는 `watcher.py` 파일에 `line 427`을 보시면
OS에 있는 트루타입 폰트를 불러오는건데요, `NanumGothic.ttf` 폰트를 불러오지 못해서 생긴 오류인것 같네요.

**Comment by adgjmptw2** [comment]
절대경로로 설정함으로 잘 되고 있습니다 감사합니다 :)
